apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp-deployment
  labels:
    app: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
      - name: scaletestapp-container
        image: shestera/scaletestapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "30Mi"
            cpu: "30m"
          limits:
            memory: "30Mi"
            cpu: "30m"
---
apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  labels:
    app: scaletestapp
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: scaletestapp