apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-app-sm
  namespace: default
  labels:
    release: prometheus-operator
spec:
  endpoints:
  - port: web
    interval: 5s
    path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: scaletestapp